name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84efde3d82ebecf44889a5fd287b9ecd6fae6fda9b4bfa48eff391439b037ea2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
