name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc480d3d7dc9c85da6b83379522af554aa1cd870cb2f2e967572861afb1aefea"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
