name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d74b6ec86c7eeab5629184023b01e78d125f6449eea8909193fda36e1e14bfa"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
