name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "658f336f5dde39bd30c30b4894a5d4f36a7e90b8d905bdaf0f68c516a9db40a0"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
