name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56823955a3079fe47d1d53ff1b0dab82f0a6cb615f0b546f691b571177808e12"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
