name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afadcefeedd269a3a855cd2555b476e3c84a741cdff947a142b855fbbdab4482"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.174"
