name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb1171fc29741a0c79c8e86bdca4b2c66dd3b1b12e68f5f03a956ea05e8fbf0d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
