name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2bfb062e2f33288af80455057a1e5a6a3228d1bad158ed626a5f796fbd0ddca"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1", "1.20.2"]
