name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da3555a02fafe937008157dac9cd2df63c29542199de7fb7c2170b7e26b20801"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
