name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d9d60f0ebd6a003be1d6bcda966da3660c13825f4c6d55faba5b3701a949fc4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
