name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9656fb1aa1b68be47d9a59a4ca6eb986618527a6696f959c193d1df0836a9dd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.134"
