name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d78a3ec9f685698bde3d15609282dd447e43b31372c65364226f8d432bd58d3d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
