name = "Fabric Science"
author = "Aetf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "420e3542bd2122574baea2fed2e8075820d1d9f4e842e7b84208abe12d97cd9d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.168"
