//priority: 2005

const sieving = {
	"minecraft:dirt": {
		string: {
			"havenpebbles:stone_pebble": 1,
			"minecraft:flint": 0.25,
			"minecraft:wheat_seeds": 0.125,
			"minecraft:carrot": 0.1,
			"minecraft:pumpkin_seeds": 0.1,
			"exdeorum:grass_seeds": 0.1,
			"minecraft:beetroot_seeds": 0.1,
			"minecraft:melon_seeds": 0.1,
			"minecraft:potato": 0.1,
			"minecraft:sugar_cane": 0.1,
			"minecraft:poisonous_potato": 0.05,
			"minecraft:bamboo": 0.04,
			"exdeorum:mycelium_spores": 0.03,
		},
		flint: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:zinc_ore_chunk": 0.3,
			"minecraft:flint": 0.3,
			"minecraft:wheat_seeds": 0.15,
			"minecraft:carrot": 0.15,
			"minecraft:pumpkin_seeds": 0.15,
			"exdeorum:grass_seeds": 0.15,
			"minecraft:beetroot_seeds": 0.1,
			"minecraft:melon_seeds": 0.15,
			"minecraft:potato": 0.15,
			"minecraft:sugar_cane": 0.15,
			"minecraft:poisonous_potato": 0.05,
			"minecraft:bamboo": 0.05,
			"exdeorum:mycelium_spores": 0.05,
			"minecraft:sweet_berries": 0.05,
			"minecraft:pink_petals": 0.03,
		},
		iron: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:zinc_ore_chunk": 0.35,
			"minecraft:flint": 0.35,
			"minecraft:wheat_seeds": 0.2,
			"minecraft:carrot": 0.2,
			"minecraft:pumpkin_seeds": 0.2,
			"exdeorum:grass_seeds": 0.2,
			"minecraft:beetroot_seeds": 0.15,
			"minecraft:melon_seeds": 0.2,
			"minecraft:potato": 0.2,
			"minecraft:sugar_cane": 0.2,
			"minecraft:poisonous_potato": 0.075,
			"minecraft:bamboo": 0.075,
			"exdeorum:mycelium_spores": 0.075,
			"minecraft:sweet_berries": 0.075,
			"minecraft:pink_petals": 0.05,
		},
		golden: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:zinc_ore_chunk": 0.4,
			"minecraft:flint": 0.4,
			"minecraft:wheat_seeds": 0.25,
			"minecraft:carrot": 0.25,
			"minecraft:pumpkin_seeds": 0.25,
			"exdeorum:grass_seeds": 0.25,
			"minecraft:beetroot_seeds": 0.2,
			"minecraft:melon_seeds": 0.25,
			"minecraft:potato": 0.25,
			"minecraft:sugar_cane": 0.25,
			"minecraft:poisonous_potato": 0.1,
			"minecraft:bamboo": 0.1,
			"exdeorum:mycelium_spores": 0.1,
			"minecraft:sweet_berries": 0.1,
			"minecraft:pink_petals": 0.075,
			"minecraft:golden_carrot": 0.015,
		},
		diamond: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:zinc_ore_chunk": 0.45,
			"minecraft:flint": 0.45,
			"minecraft:wheat_seeds": 0.3,
			"minecraft:carrot": 0.3,
			"minecraft:pumpkin_seeds": 0.3,
			"exdeorum:grass_seeds": 0.3,
			"minecraft:beetroot_seeds": 0.25,
			"minecraft:melon_seeds": 0.3,
			"minecraft:potato": 0.3,
			"minecraft:sugar_cane": 0.3,
			"minecraft:poisonous_potato": 0.15,
			"minecraft:bamboo": 0.15,
			"exdeorum:mycelium_spores": 0.15,
			"minecraft:sweet_berries": 0.15,
			"minecraft:pink_petals": 0.1,
			"minecraft:golden_carrot": 0.02,
		},
		netherite: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:zinc_ore_chunk": 0.5,
			"minecraft:flint": 0.5,
			"minecraft:wheat_seeds": 0.35,
			"minecraft:carrot": 0.35,
			"minecraft:pumpkin_seeds": 0.35,
			"exdeorum:grass_seeds": 0.35,
			"minecraft:beetroot_seeds": 0.3,
			"minecraft:melon_seeds": 0.35,
			"minecraft:potato": 0.35,
			"minecraft:sugar_cane": 0.35,
			"minecraft:poisonous_potato": 0.2,
			"minecraft:bamboo": 0.2,
			"exdeorum:mycelium_spores": 0.2,
			"minecraft:sweet_berries": 0.2,
			"minecraft:pink_petals": 0.15,
			"minecraft:golden_carrot": 0.025,
			"minecraft:golden_apple": 0.0025,
		},
	},
	"minecraft:soul_sand": {
		string: {
			"minecraft:bone": 0.08,
			"minecraft:gunpowder": 0.07,
			"minecraft:nether_wart": 0.06,
		},
		flint: {
			"minecraft:bone": 0.1,
			"minecraft:gunpowder": 0.09,
			"minecraft:nether_wart": 0.08,
			"exdeorum:warped_nylium_spores": 0.03,
			"exdeorum:crimson_nylium_spores": 0.03,
		},
		iron: {
			"minecraft:bone": 0.12,
			"minecraft:gunpowder": 0.11,
			"minecraft:nether_wart": 0.1,
			"exdeorum:warped_nylium_spores": 0.05,
			"exdeorum:crimson_nylium_spores": 0.05,
			"minecraft:quartz": 0.15,
		},
		golden: {
			"minecraft:bone": 0.15,
			"minecraft:gunpowder": 0.13,
			"minecraft:nether_wart": 0.12,
			"exdeorum:warped_nylium_spores": 0.07,
			"exdeorum:crimson_nylium_spores": 0.07,
			"minecraft:quartz": 0.175,
		},
		diamond: {
			"minecraft:bone": 0.2,
			"minecraft:gunpowder": 0.15,
			"minecraft:nether_wart": 0.15,
			"exdeorum:warped_nylium_spores": 0.1,
			"exdeorum:crimson_nylium_spores": 0.1,
			"minecraft:quartz": 0.2,
		},
		netherite: {
			"minecraft:bone": 0.25,
			"minecraft:gunpowder": 0.2,
			"minecraft:nether_wart": 0.2,
			"exdeorum:warped_nylium_spores": 0.15,
			"exdeorum:crimson_nylium_spores": 0.15,
			"minecraft:quartz": 0.25,
		},
	},
	"minecraft:sand": {
		string: {
			"minecraft:flint": 0.2,
			"minecraft:cactus": 0.13,
			"minecraft:kelp": 0.1,
			"minecraft:dead_bush": 0.08,
			"minecraft:sea_pickle": 0.05,
		},
		flint: {
			"minecraft:flint": 0.22,
			"minecraft:cactus": 0.15,
			"minecraft:kelp": 0.12,
			"minecraft:dead_bush": 0.1,
			"minecraft:sea_pickle": 0.07,
		},
		iron: {
			"minecraft:flint": 0.24,
			"minecraft:cactus": 0.17,
			"minecraft:kelp": 0.14,
			"minecraft:dead_bush": 0.12,
			"minecraft:sea_pickle": 0.09,
			"minecraft:prismarine_shard": 0.06,
			"minecraft:prismarine_crystals": 0.06,
		},
		golden: {
			"minecraft:flint": 0.26,
			"minecraft:cactus": 0.19,
			"minecraft:kelp": 0.16,
			"minecraft:dead_bush": 0.14,
			"minecraft:sea_pickle": 0.11,
			"minecraft:prismarine_shard": 0.08,
			"minecraft:prismarine_crystals": 0.08,
		},
		diamond: {
			"minecraft:flint": 0.3,
			"minecraft:cactus": 0.23,
			"minecraft:kelp": 0.2,
			"minecraft:dead_bush": 0.18,
			"minecraft:sea_pickle": 0.15,
			"minecraft:prismarine_shard": 0.12,
			"minecraft:prismarine_crystals": 0.12,
		},
		netherite: {
			"minecraft:flint": 0.35,
			"minecraft:cactus": 0.25,
			"minecraft:kelp": 0.25,
			"minecraft:dead_bush": 0.2,
			"minecraft:sea_pickle": 0.2,
			"minecraft:prismarine_shard": 0.15,
			"minecraft:prismarine_crystals": 0.15,
		},
	},
	"exdeorum:crushed_deepslate": {
		string: {
			"exdeorum:deepslate_pebble": 1,
		},
		flint: {
			"exdeorum:deepslate_pebble": 1,
			"exdeorum:calcite_pebble": 1,
		},
		iron: {
			"exdeorum:deepslate_pebble": 1,
			"exdeorum:calcite_pebble": 1,
			"exdeorum:basalt_pebble": 1,
		},
		golden: {
			"exdeorum:deepslate_pebble": 1,
			"exdeorum:calcite_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"exdeorum:tuff_pebble": 1,
		},
		diamond: {
			"exdeorum:deepslate_pebble": 1,
			"exdeorum:calcite_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"exdeorum:tuff_pebble": 1,
		},
		netherite: {
			"exdeorum:deepslate_pebble": 1,
			"exdeorum:calcite_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"exdeorum:tuff_pebble": 1,
		},
	},
	"minecraft:red_sand": {
		string: {
			"minecraft:cactus": 0.12,
			"minecraft:amethyst_shard": 0.1,
			"minecraft:redstone": 0.08,
			"minecraft:dead_bush": 0.06,
		},
		flint: {
			"minecraft:cactus": 0.14,
			"minecraft:amethyst_shard": 0.12,
			"minecraft:redstone": 0.1,
			"minecraft:dead_bush": 0.08,
		},
		iron: {
			"minecraft:cactus": 0.16,
			"minecraft:amethyst_shard": 0.14,
			"minecraft:redstone": 0.12,
			"minecraft:dead_bush": 0.1,
		},
		golden: {
			"minecraft:cactus": 0.18,
			"minecraft:amethyst_shard": 0.16,
			"minecraft:redstone": 0.14,
			"minecraft:dead_bush": 0.12,
		},
		diamond: {
			"minecraft:cactus": 0.2,
			"minecraft:amethyst_shard": 0.18,
			"minecraft:redstone": 0.16,
			"minecraft:dead_bush": 0.14,
		},
		netherite: {
			"minecraft:cactus": 0.25,
			"minecraft:amethyst_shard": 0.2,
			"minecraft:redstone": 0.2,
			"minecraft:dead_bush": 0.2,
		},
	},
	"minecraft:gravel": {
		string: {
			"havenpebbles:stone_pebble": 1,
			"minecraft:flint": 0.2,
			"minecraft:coal": 0.1,
		},
		flint: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"minecraft:flint": 0.25,
			"minecraft:coal": 0.125,
			"minecraft:pointed_dripstone": 0.15,
		},
		iron: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"minecraft:flint": 0.3,
			"minecraft:coal": 0.15,
			"minecraft:pointed_dripstone": 0.175,
		},
		golden: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"minecraft:flint": 0.35,
			"minecraft:coal": 0.175,
			"minecraft:pointed_dripstone": 0.2,
		},
		diamond: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"minecraft:flint": 0.4,
			"minecraft:coal": 0.2,
			"minecraft:pointed_dripstone": 0.225,
		},
		netherite: {
			"havenpebbles:stone_pebble": 1,
			"exdeorum:andesite_pebble": 1,
			"exdeorum:granite_pebble": 1,
			"exdeorum:diorite_pebble": 1,
			"minecraft:flint": 0.45,
			"minecraft:coal": 0.25,
			"minecraft:pointed_dripstone": 0.25,
		},
	},
	"exdeorum:dust": {
		string: {
			"minecraft:bone_meal": 0.1,
			"minecraft:lapis_lazuli": 0.1,
			"minecraft:gunpowder": 0.1,
			"minecraft:redstone": 0.06,
		},
		flint: {
			"minecraft:bone_meal": 0.125,
			"minecraft:lapis_lazuli": 0.125,
			"minecraft:gunpowder": 0.125,
			"minecraft:redstone": 0.1,
		},
		iron: {
			"minecraft:bone_meal": 0.15,
			"minecraft:lapis_lazuli": 0.15,
			"minecraft:gunpowder": 0.15,
			"minecraft:redstone": 0.125,
		},
		golden: {
			"minecraft:bone_meal": 0.175,
			"minecraft:lapis_lazuli": 0.175,
			"minecraft:gunpowder": 0.175,
			"minecraft:redstone": 0.15,
		},
		diamond: {
			"minecraft:bone_meal": 0.2,
			"minecraft:lapis_lazuli": 0.2,
			"minecraft:gunpowder": 0.2,
			"minecraft:redstone": 0.175,
		},
		netherite: {
			"minecraft:bone_meal": 0.25,
			"minecraft:lapis_lazuli": 0.25,
			"minecraft:gunpowder": 0.25,
			"minecraft:redstone": 0.2,
		},
	},
	"exdeorum:crushed_blackstone": {
		string: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.075,
			"minecraft:black_dye": 0.075,
			"tconstruct:debris_nugget": 0.01,
		},
		flint: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.1,
			"minecraft:black_dye": 0.1,
			"tconstruct:debris_nugget": 0.02,
		},
		iron: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.125,
			"minecraft:black_dye": 0.125,
			"tconstruct:debris_nugget": 0.03,
		},
		golden: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.15,
			"minecraft:black_dye": 0.15,
			"tconstruct:debris_nugget": 0.04,
		},
		diamond: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.175,
			"minecraft:black_dye": 0.175,
			"tconstruct:debris_nugget": 0.05,
		},
		netherite: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.2,
			"minecraft:black_dye": 0.2,
			"tconstruct:debris_nugget": 0.15,
		},
	},
	"minecraft:moss_block": {
		string: {
			"minecraft:oak_sapling": 0.075,
			"minecraft:spruce_sapling": 0.075,
			"minecraft:cherry_sapling": 0.075,
			"minecraft:birch_sapling": 0.075,
			"minecraft:acacia_sapling": 0.075,
			"minecraft:jungle_sapling": 0.075,
			"minecraft:dark_oak_sapling": 0.075,
			"minecraft:mangrove_propagule": 0.075,
			"minecraft:azalea": 0.05,
			"minecraft:small_dripleaf": 0.05,
			"minecraft:big_dripleaf": 0.05,
			"minecraft:glow_berries": 0.04,
			"minecraft:spore_blossom": 0.03,
		},
		flint: {
			"minecraft:oak_sapling": 0.1,
			"minecraft:spruce_sapling": 0.1,
			"minecraft:cherry_sapling": 0.1,
			"minecraft:birch_sapling": 0.1,
			"minecraft:acacia_sapling": 0.1,
			"minecraft:jungle_sapling": 0.1,
			"minecraft:dark_oak_sapling": 0.1,
			"minecraft:mangrove_propagule": 0.1,
			"minecraft:azalea": 0.06,
			"minecraft:small_dripleaf": 0.06,
			"minecraft:big_dripleaf": 0.06,
			"minecraft:glow_berries": 0.05,
			"minecraft:spore_blossom": 0.04,
			"minecraft:glow_lichen": 0.04,
			"minecraft:lily_pad": 0.04,
			"minecraft:flowering_azalea": 0.03,
			"minecraft:sweet_berries": 0.03,
		},
		iron: {
			"minecraft:oak_sapling": 0.125,
			"minecraft:spruce_sapling": 0.125,
			"minecraft:cherry_sapling": 0.125,
			"minecraft:birch_sapling": 0.125,
			"minecraft:acacia_sapling": 0.125,
			"minecraft:jungle_sapling": 0.125,
			"minecraft:dark_oak_sapling": 0.125,
			"minecraft:mangrove_propagule": 0.125,
			"minecraft:azalea": 0.07,
			"minecraft:small_dripleaf": 0.07,
			"minecraft:big_dripleaf": 0.07,
			"minecraft:glow_berries": 0.06,
			"minecraft:spore_blossom": 0.05,
			"minecraft:glow_lichen": 0.05,
			"minecraft:lily_pad": 0.05,
			"minecraft:flowering_azalea": 0.04,
			"minecraft:sweet_berries": 0.04,
		},
		golden: {
			"minecraft:oak_sapling": 0.15,
			"minecraft:spruce_sapling": 0.15,
			"minecraft:cherry_sapling": 0.15,
			"minecraft:birch_sapling": 0.15,
			"minecraft:acacia_sapling": 0.15,
			"minecraft:jungle_sapling": 0.15,
			"minecraft:dark_oak_sapling": 0.15,
			"minecraft:mangrove_propagule": 0.15,
			"minecraft:azalea": 0.08,
			"minecraft:small_dripleaf": 0.08,
			"minecraft:big_dripleaf": 0.08,
			"minecraft:glow_berries": 0.07,
			"minecraft:spore_blossom": 0.06,
			"minecraft:glow_lichen": 0.06,
			"minecraft:lily_pad": 0.06,
			"minecraft:flowering_azalea": 0.05,
			"minecraft:sweet_berries": 0.05,
		},
		diamond: {
			"minecraft:oak_sapling": 0.175,
			"minecraft:spruce_sapling": 0.175,
			"minecraft:cherry_sapling": 0.175,
			"minecraft:birch_sapling": 0.175,
			"minecraft:acacia_sapling": 0.175,
			"minecraft:jungle_sapling": 0.175,
			"minecraft:dark_oak_sapling": 0.175,
			"minecraft:mangrove_propagule": 0.175,
			"minecraft:azalea": 0.09,
			"minecraft:small_dripleaf": 0.09,
			"minecraft:big_dripleaf": 0.09,
			"minecraft:glow_berries": 0.08,
			"minecraft:spore_blossom": 0.07,
			"minecraft:glow_lichen": 0.07,
			"minecraft:lily_pad": 0.07,
			"minecraft:flowering_azalea": 0.06,
			"minecraft:sweet_berries": 0.06,
		},
		netherite: {
			"minecraft:oak_sapling": 0.2,
			"minecraft:spruce_sapling": 0.2,
			"minecraft:cherry_sapling": 0.2,
			"minecraft:birch_sapling": 0.2,
			"minecraft:acacia_sapling": 0.2,
			"minecraft:jungle_sapling": 0.2,
			"minecraft:dark_oak_sapling": 0.2,
			"minecraft:mangrove_propagule": 0.2,
			"minecraft:azalea": 0.1,
			"minecraft:small_dripleaf": 0.1,
			"minecraft:big_dripleaf": 0.1,
			"minecraft:glow_berries": 0.1,
			"minecraft:spore_blossom": 0.1,
			"minecraft:glow_lichen": 0.1,
			"minecraft:lily_pad": 0.1,
			"minecraft:flowering_azalea": 0.1,
			"minecraft:sweet_berries": 0.1,
		},
	},
	"exdeorum:crushed_netherrack": {
		string: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.08,
			"exdeorum:warped_nylium_spores": 0.05,
			"exdeorum:crimson_nylium_spores": 0.05,
		},
		flint: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.09,
			"exdeorum:warped_nylium_spores": 0.07,
			"exdeorum:crimson_nylium_spores": 0.07,
		},
		iron: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.1,
			"exdeorum:warped_nylium_spores": 0.09,
			"exdeorum:crimson_nylium_spores": 0.09,
			"minecraft:quartz": 0.11,
		},
		golden: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.125,
			"exdeorum:warped_nylium_spores": 0.1,
			"exdeorum:crimson_nylium_spores": 0.1,
			"minecraft:quartz": 0.135,
		},
		diamond: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.15,
			"exdeorum:warped_nylium_spores": 0.11,
			"exdeorum:crimson_nylium_spores": 0.11,
			"minecraft:quartz": 0.165,
		},
		netherite: {
			"exdeorum:blackstone_pebble": 1,
			"exdeorum:basalt_pebble": 1,
			"minecraft:gunpowder": 0.2,
			"exdeorum:warped_nylium_spores": 0.15,
			"exdeorum:crimson_nylium_spores": 0.15,
			"minecraft:quartz": 0.2,
		},
	},
	"exdeorum:crushed_end_stone": {
		string: {
			"minecraft:chorus_fruit": 0.09,
			"minecraft:ender_pearl": 0.07,
		},
		flint: {
			"minecraft:chorus_fruit": 0.11,
			"minecraft:ender_pearl": 0.8,
		},
		iron: {
			"minecraft:chorus_fruit": 0.13,
			"minecraft:ender_pearl": 0.1,
		},
		golden: {
			"minecraft:chorus_fruit": 0.15,
			"minecraft:ender_pearl": 0.12,
		},
		diamond: {
			"minecraft:chorus_fruit": 0.175,
			"minecraft:ender_pearl": 0.15,
			"minecraft:sculk": 0.1,
		},
		netherite: {
			"minecraft:chorus_fruit": 0.25,
			"minecraft:ender_pearl": 0.2,
			"minecraft:sculk": 0.25,
			"minecraft:echo_shard": 0.03,
			"minecraft:chorus_flower": 0.025,
			"minecraft:sculk_shrieker": 0.01,
		},
	},
	"kubejs:crushed_sky_stone": {
		string: {
			"kubejs:certus_seed": 0.01,
		},
		flint: {
			"kubejs:certus_seed": 0.025,
		},
		iron: {
			"kubejs:certus_seed": 0.05,
		},
		golden: {
			"kubejs:certus_seed": 0.1,
		},
		diamond: {
			"kubejs:certus_seed": 0.125,
		},
		netherite: {
			"kubejs:certus_seed": 0.2,
		},
	},
}

ServerEvents.recipes(event => {
	removeRecipeByType(event, [
		EXD("sieve"),
		EXD("compressed_sieve"),
	])
	
	function findMeshNumber(meshStr) {
		let meshEq
		switch (meshStr) {
			case "string":
				meshEq = 1;
				break;
			case "flint":
				meshEq = 2;
				break;
			case "iron":
				meshEq = 3;
				break;
			case "golden":
				meshEq = 4;
				break;
			case "diamond":
				meshEq = 5;
				break;
			case "netherite":
				meshEq = 6;
				break;
		}
		
		return meshEq;
	}
	
	for (const block in sieving) {
		for (const mesh in sieving[block]) {
			for (const item in sieving[block][mesh]) {
				//exdeorum sieving
				//(e, output, input, mesh, chance)
				customRecipes.exdeorum.sieving(event, item, block, findMeshNumber(mesh), sieving[block][mesh][item])
			}
			
			//create sifting
			if (mesh == "flint") continue
			let items = Object.keys(sieving[block][mesh]).map(item => `${item} ${sieving[block][mesh][item]}`)
			
			//(e, outputArr, item, mesh, ticks)
			customRecipes.create.sifting(event, items, block, findMeshNumber(mesh))
		}
	}
})