ClientEvents.lang('en_us', event => {
	event.renameBlock('cobblefordays:tier_1', "Cobblestone Generator (Tier 1)")
	event.renameBlock('cobblefordays:tier_2', "Cobblestone Generator (Tier 2)")
	event.renameBlock('cobblefordays:tier_3', "Cobblestone Generator (Tier 3)")
	event.renameBlock('cobblefordays:tier_4', "Cobblestone Generator (Tier 4)")
	event.renameBlock('cobblefordays:tier_5', "Cobblestone Generator (Tier 5)")

	event.renameItem('ironfurnaces:rainbow_coal', "The Ultimate Fuel")
	event.renameItem('ad_astra:cheese', "Lunar Cheese")

	event.renameBlock('miniutilities:white_lapis_caelestis', "White AntiBlock")
	event.renameBlock('miniutilities:light_gray_lapis_caelestis', "Light Gray AntiBlock")
	event.renameBlock('miniutilities:gray_lapis_caelestis', "Gray AntiBlock")
	event.renameBlock('miniutilities:black_lapis_caelestis', "Black AntiBlock")
	event.renameBlock('miniutilities:red_lapis_caelestis', "Red AntiBlock")
	event.renameBlock('miniutilities:orange_lapis_caelestis', "Orange AntiBlock")
	event.renameBlock('miniutilities:yellow_lapis_caelestis', "Yellow AntiBlock")
	event.renameBlock('miniutilities:lime_lapis_caelestis', "Lime AntiBlock")
	event.renameBlock('miniutilities:green_lapis_caelestis', "Green AntiBlock")
	event.renameBlock('miniutilities:light_blue_lapis_caelestis', "Light Blue AntiBlock")
	event.renameBlock('miniutilities:cyan_lapis_caelestis', "Cyan AntiBlock")
	event.renameBlock('miniutilities:blue_lapis_caelestis', "Blue AntiBlock")
	event.renameBlock('miniutilities:purple_lapis_caelestis', "Purple AntiBlock")
	event.renameBlock('miniutilities:magenta_lapis_caelestis', "Magenta AntiBlock")
	event.renameBlock('miniutilities:pink_lapis_caelestis', "Pink AntiBlock")
	event.renameBlock('miniutilities:brown_lapis_caelestis', "Brown AntiBlock")
	event.renameItem('miniutilities:angel_ring', "Advanced Angel Ring")
	event.renameItem('miniutilities:gold_angel_ring', "Gold Advanced Angel Ring")
	event.renameItem('miniutilities:ender_dragon_angel_ring', "Ender Dragon Advanced Angel Ring")
	event.renameItem('miniutilities:feather_angel_ring', "Feather Advanced Angel Ring")
	event.renameItem('miniutilities:bat_angel_ring', "Bat Advanced Angel Ring")
	event.renameItem('miniutilities:peacock_angel_ring', "Peacock Advanced Angel Ring")
	
	event.renameBlock('flopper:flopper', "Fluid Hopper")
	
	event.renameItem('create:brass_hand', "Golden Hand")
	event.renameBlock('create:item_vault', "Item Vault (Horizontal)")
	event.renameBlock('create:fluid_tank', "Fluid Tank (Vertical)")
	event.renameBlock('create:creative_fluid_tank', "Creative Fluid Tank (Vertical)")
	
	event.renameItem('minecraft:shield', "Iron Shield")
	event.renameItem('minecraft:bucket', "Iron Bucket")
	
	event.renameBlock('createsifter:crushed_end_stone', "Crushed End Stone")
	event.renameBlock('createsifter:dust', "Dust Block")
	event.renameBlock('createsifter:sifter', "Andesite Sifter")
	event.renameItem('createsifter:andesite_mesh', "Mechanical Netherite Mesh")
	event.renameItem('createsifter:brass_mesh', "Mechanical Golden Mesh")
	event.renameItem('createsifter:custom_mesh', "Mechanical Diamond Mesh")
	event.renameItem('createsifter:string_mesh', "Mechanical String Mesh")
	event.renameItem('createsifter:zinc_mesh', "Mechanical Iron Mesh")
	
	event.renameBlock('ae2:not_so_mysterious_cube', "Calculation Machine")
	
	event.renameBlock('extendedcrafting:frame', "Embedded Machine")
	
	event.renameBlock('mekanism:structural_glass', "Witherproof Structural Glass")
	event.renameItem('mekanism:reprocessed_fissile_fragment', "Irradiated Pellet")
	event.renameBlock('mekanism:steel_casing', "Electric Machine")
	
	event.renameBlock('ad_astra:steel_door', "Iron Spaceship Door")
	event.renameBlock('ad_astra:reinforced_door', "Iron Vault Double Door")
	event.renameBlock('ad_astra:airlock', "Iron Airlock Double Door")
	event.renameBlock('ad_astra:steel_sliding_door', "Iron Dark Sliding Double Door")
	event.renameBlock('ad_astra:iron_sliding_door', "Iron Bright Sliding Double Door")
	event.renameBlock('ad_astra:steel_trapdoor', "Iron Spaceship Trapdoor")
	
	event.renameBlock('fluxnetworks:flux_point', "Flux Point (Export)")
	event.renameBlock('fluxnetworks:flux_plug', "Flux Plug (Import)")
	
	event.renameItem('endrem:black_eye', "Sealed Eye")
	event.renameItem('endrem:cold_eye', "Precise Eye")
	event.renameItem('endrem:corrupted_eye', "Electric Eye")
	event.renameItem('endrem:lost_eye', "Inductive Eye")
	event.renameItem('endrem:nether_eye', "Calculated Eye")
	event.renameItem('endrem:rogue_eye', "Abstruse Eye")
	event.renameItem('endrem:cursed_eye', "Integrated Eye")
	event.renameItem('endrem:evil_eye', "Portable Eye")
	event.renameItem('endrem:guardian_eye', "Applied Eye")
	event.renameItem('endrem:magical_eye', "Killer's Eye")
	event.renameItem('endrem:wither_eye', "Cook's Eye")
	event.renameItem('endrem:witch_eye', "Hunter's Eye")
	event.renameItem('endrem:exotic_eye', "Embedded Eye")
	event.renameItem('endrem:cryptic_eye', "Experienced Eye")
	
	event.renameItem('projecte:swiftwolf_rending_gale', "Switfwolf's Rending Gale (Angel Ring)")
	
	event.renameBlock('enderio:enderman_head', "Suspicious Enderman Head")
	
	event.renameItem('industrialrenewal:ingot_steel', "Cast Iron Ingot")
	event.renameItem('industrialrenewal:stick_steel', "Cast Iron Rod")
	event.renameItem('industrialrenewal:drill_steel', "Cast Iron Drill")
	event.renameBlock('industrialrenewal:catwalk_steel_pillar', "Cast Iron Pillar")
	event.renameBlock('industrialrenewal:catwalk_steel', "Cast Iron Catwalk")
	event.renameBlock('industrialrenewal:catwalk_stair_steel', "Cast Iron Stair")
	event.renameBlock('industrialrenewal:catwalk_ladder_steel', "Caged Cast Iron Ladder")
	event.renameBlock('industrialrenewal:block_steel', "Cast Iron Block")
	event.renameBlock('industrialrenewal:brace_steel', "Cast Iron Brace Beam")
	event.renameBlock('industrialrenewal:catwalk_column_steel', "Cast Iron Column")
	event.renameBlock('industrialrenewal:handrail_steel', "Cast Iron Handrail")
	event.renameBlock('industrialrenewal:razor_wire', "Barbed Wire")
	event.renameItem('industrialrenewal:battery_lithium', "Industrial Battery")
	event.renameBlock('industrialrenewal:fluid_tank', "Industrial Fluid Tank")
	event.renameBlock('industrialrenewal:concrete', "Industrial Concrete")
	event.renameItem('industrialrenewal:screwdriver', 'Industrial Screwdriver')
	
	event.renameBlock('create_connected:fluid_vessel', "Fluid Tank (Horizontal)")
	event.renameBlock('create_connected:creative_fluid_vessel', "Creative Fluid Tank (Horizontal)")
	event.renameBlock('create_connected:item_silo', "Item Vault (Vertical)")
	
	event.renameItem('morebuckets:obsidian_bucket', "Netherite Bucket")
	
	event.renameItem('powah:crystal_nitro', "Overcharged Fluix Crystal")
	event.renameBlock('powah:nitro_crystal_block', "Overcharged Fluix Crystal Block")
	event.renameItem('powah:steel_energized', "Energized Alloy Ingot")
	event.renameBlock('powah:energized_steel_block', "Block of Energized Alloy")
});

