
[general]
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = true

[CraftingMapper]

	[CraftingMapper.Smithing]
		#Maps smithing recipes.
		enabled = true

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe, SingleItemRecipe, or SmithingRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = true

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = true

[permissions]

	[permissions.appliede]
		#Allow mod 'appliede' to set and or remove values for mod 'ae2'. Options: [both, set, remove, none]
		ae2 = "both"

[APICustomEMCMapper]

	[APICustomEMCMapper.priority]
		#Priority for this mod
		appliede = 1

[enabledMappers]
	#Set EMC=0 for everything in the forge:raw_materials tag
	RawOresBlacklistMapper = false
	#(AppliedE) Maps Applied Energistics 2 matter condenser results.
	AE2MatterCondenser = true
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = false
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = false
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true
	#Set EMC=0 for everything in the forge:ores tag
	OresBlacklistMapper = false
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = false
	#Add Conversions for all weathered copper variants
	WeatheredCopperMapper = false
	#(AppliedE) Maps Applied Energistics 2 cable facades.
	AE2FacadeMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true
	#(AppliedE) Maps Applied Energistics 2 P2P tunnels.
	AE2P2PTunnels = true
	#Allows KubeJS ProjectE to function
	KubeJSProjectE = true

