#Whether highlighting of sleep-preventing monsters is enabled. Set this to false to disable the feature.
highlight_mobs = true
#How long the highlight effect will last, in ticks.
#Range: > 1
highlight_duration = 60

