enableNoEmiMessage = true
spawnWithGuideBook = true
respawnWithGuideBook = true
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = false
enableAe2Integration = true
enableFtbQuestsIntegration = true
enableDefaultOreGenTooltips = true
datagenOnStartup = false
loadRuntimeGeneratedResources = true
removeIndustrialistTrades = false
maxDistillationTowerHeight = 9
enableInterMachineConnectedTextures = true
armorHudYPosition = 4
baseItemPipeTransfer = 16
stonecutterToCuttingMachine = true
compostableToPlantOil = true
