// priority: 0

ServerEvents.recipes(event => {
	//blaze
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('blaze')
		.input(Item.of(MC("netherrack"), 1))
		.input(Item.of(MC("blaze_powder"), 3))
		.input(Item.of(MC("glowstone_dust"), 4))
		.input(Item.of(MC("emerald"), 1))
		.input(Item.of(MC("redstone"), 2))
		.input(Item.of(MC("nether_wart"), 1))
		.input(Item.of(MC("orange_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//enderman
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('enderman')
		.input(Item.of(MC("ender_pearl"), 1))
		.input(Item.of(MC("redstone"), 4))
		.input(Item.of(MC("emerald"), 1))
		.input(Item.of(MC("glowstone_dust"), 9))
		.input(Item.of(MC("nether_wart"), 1))
		.input(Item.of(MC("black_dye"), 2))
		.recipeTime(200)
		.dayTime('night')
	//guardian
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('guardian')
		.input(Item.of(MC("prismarine_crystals"), 1))
		.input(Item.of(MC("redstone"), 9))
		.input(Item.of(MC("emerald"), 3))
		.input(Item.of(MC("glowstone_dust"), 2))
		.input(Item.of(MC("cyan_dye"), 3))
		.input(MC("#fishes"))
		.recipeTime(200)
		.dayTime('night')
	//shulker
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('shulker')
		.input(Item.of(MC("end_stone"), 8))
		.input(Item.of(MC("ender_pearl"), 2))
		.input(Item.of(MC("glowstone_dust"), 7))
		.input(Item.of(MC("emerald"), 3))
		.input(Item.of(MC("purple_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//ocelot
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('ocelot'))
		.input(Item.of(MC("emerald"), 5))
		.input(Item.of(MC("dirt"), 1))
		.input(Item.of(MC("redstone"), 3))
		.input(MC("#fishes"))
		.input(Item.of(MC("orange_dye"), 1))
		.input(Item.of(MC("string"), 4))
		.recipeTime(200)
		.dayTime('day')
	//panda
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('panda'))
		.input(Item.of(MC("gold_ingot"), 16))
		.input(Item.of(MC("bamboo"), 16))
		.input(Item.of(MC("snowball"), 4))
		.input(Item.of(MC("redstone"), 6))
		.input(Item.of(MC("black_dye"), 1))
		.input(Item.of(MC("white_dye"), 1))
		.recipeTime(200)
		.dayTime('day')
	//strider
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('strider'))
		.input(Item.of(TCT("cobalt_ingot"), 8))
		.input(Item.of(MC("lava_bucket"), 1))
		.input(Item.of(MC("gold_nugget"), 3))
		.input(Item.of(MC("quartz"), 9))
		.input(Item.of(MC("warped_nylium"), 1))
		.input(Item.of(MC("amethyst_shard"), 5))
		.input(Item.of(MC("pink_dye"), 1))
		.input(Item.of(MC("warped_fungus"), 2))
		.recipeTime(200)
	//hoglin
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('hoglin'))
		.input(Item.of(MC("crimson_nylium"), 1))
		.input(Item.of(MC("gold_ingot"), 4))
		.input(Item.of(MC("quartz"), 4))
		.input(Item.of(MC("lapis_lazuli"), 7))
		.input(Item.of(MC("brown_dye"), 1))
		.input(Item.of(MC("crimson_fungus"), 2))
		.recipeTime(200)
		.dayTime('night')
	//frog
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('frog'))
		.input(Item.of(MC("iron_ingot"), 8))
		.input(Item.of(MC("slime_ball"), 2))
		.input(Item.of(MC("water_bucket"), 1))
		.input(Item.of(MC("emerald"), 3))
		.input(Item.of(MC("green_dye"), 1))
		.recipeTime(200)
		.dayTime('day')
	//camel
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('camel'))
		.input(Item.of(MC("gold_ingot"), 9))
		.input(Item.of(MC("cactus"), 4))
		.input(Item.of(MC("sand"), 8))
		.input(Item.of(MC("emerald"), 3))
		.input(Item.of(MC("yellow_dye"), 1))
		.recipeTime(200)
		.dayTime('day')
	//warden
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('warden'))
		.input(Item.of(MC("sculk_shrieker"), 4))
		.input(Item.of(MC("gold_ingot"), 32))
		.input(Item.of(MC("echo_shard"), 16))
		.input(Item.of(MC("emerald"), 16))
		.input(Item.of(MC("black_dye"), 5))
		.blockBelow(MC('sculk_shrieker'))
		.sacrifice('goat', 3)
		.sacrificeRegion(7, 7)
		.recipeTime(200)
		.dayTime('night')
	//elder_guardian
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('elder_guardian'))
		.input(Item.of(MC("wet_sponge"), 8))
		.input(Item.of(MC("gold_ingot"), 32))
		.input(Item.of(MC("sponge"), 16))
		.input(Item.of(MC("emerald"), 16))
		.input(Item.of(MC("cyan_dye"), 5))
		.recipeTime(200)
		.blockBelow(MC('wet_sponge'))
		.sacrifice('guardian', 3)
		.sacrificeRegion(7, 7)
		.dayTime('night')
	//snow golem
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(MC('snow_golem'))
		.input(Item.of(MC("white_dye"), 7))
		.input(Item.of(MC("glowstone_dust"), 16))
		.input(Item.of(MC("emerald"), 4))
		.input(Item.of(MC("gold_ingot"), 14))
		.input(Item.of(MC("blue_ice"), 16))
		.recipeTime(200)
		.dayTime('day')
	//vindicator
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('vindicator')
		.input(Item.of(MC("iron_axe"), 1))
		.input(Item.of(MC("redstone"), 12))
		.input(Item.of(MC("emerald"), 3))
		.input(Item.of(CR("experience_nugget"), 12))
		.input(Item.of(MC("glowstone_dust"), 8))
		.input(Item.of(MC("dirt"), 1))
		.input(Item.of(MC("black_dye"), 1))
		.blockBelow(MC('dirt'))
		.recipeTime(200)
	//wandering trader
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('wandering_trader')
		.input(Item.of(MC("water_bucket"), 1))
		.input(Item.of(CR("experience_nugget"), 16))
		.input(Item.of(PET("pure_emerald"), 8))
		.input(Item.of(MC("dirt"), 1))
		.input(Item.of(MC("blue_dye"), 1))
		.recipeTime(200)
		.blockBelow(MC('dirt'))
		.dayTime('day')
	//evoker
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('evoker')
		.input(Item.of(MC("netherite_scrap"), 6))
		.input(Item.of(AP("gem_dust"), 2))
		.input(Item.of(CR("experience_nugget"), 16))
		.input(Item.of(MC("emerald"), 4))
		.input(Item.of(MC("grass_block"), 8))
		.input(Item.of(MC("gray_dye"), 7))
		.sacrifice('villager', 1)
		.sacrificeRegion(7, 7)
		.recipeTime(200)
		.dayTime('night')
	//mimic
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput(ART('mimic'))
		.input(Item.of(MC("grass_block"), 16))
		.input(Item.of(CR("experience_nugget"), 16))
		.input(Item.of(MC("nether_star"), 1))
		.input(Item.of(MC("emerald"), 16))
		.input(Item.of(MC("brown_dye"), 9))
		.input(Item.of(AP("gem_dust"), 1))
		.input(ART("#artifacts"))
		.recipeTime(200)
		.dayTime('night')
	//zombie
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('zombie')
		.input(Item.of(MC("grass_block"), 1))
		.input(Item.of(CR("experience_nugget"), 3))
		.input(Item.of(MC("iron_ingot"), 1))
		.input(Item.of(MC("redstone"), 2))
		.input(Item.of(MC("green_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//husk
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('husk')
		.input(Item.of(MC("grass_block"), 1))
		.input(Item.of(CR("experience_nugget"), 3))
		.input(Item.of(MC("iron_ingot"), 1))
		.input(Item.of(MC("redstone"), 2))
		.input(Item.of(MC("brown_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//drowned
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('drowned')
		.input(Item.of(MC("grass_block"), 1))
		.input(Item.of(CR("experience_nugget"), 3))
		.input(Item.of(MC("iron_ingot"), 1))
		.input(Item.of(MC("redstone"), 1))
		.input(Item.of(MC("kelp"), 3))
		.input(Item.of(MC("water_bucket"), 1))
		.input(Item.of(MC("cyan_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//spider
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('spider')
		.input(Item.of(MC("stone"), 4))
		.input(Item.of(MC("string"), 6))
		.input(Item.of(CR("experience_nugget"), 2))
		.input(Item.of(MC("iron_ingot"), 4))
		.input(Item.of(MC("redstone"), 2))
		.input(Item.of(MC("black_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//cave spider
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('cave_spider')
		.input(Item.of(MC("stone"), 4))
		.input(Item.of(MC("string"), 6))
		.input(Item.of(CR("experience_nugget"), 2))
		.input(Item.of(MC("iron_ingot"), 4))
		.input(Item.of(MC("redstone"), 2))
		.input(Item.of(MC("green_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//piglin
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('piglin')
		.input(Item.of(MC("magma_block"), 1))
		.input(Item.of(MC("golden_sword"), 1))
		.input(Item.of(CR("experience_nugget"), 4))
		.input(Item.of(MC("gold_ingot"), 8))
		.input(Item.of(MC("quartz"), 2))
		.input(Item.of(MC("orange_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//piglin brute
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('piglin_brute')
		.input(Item.of(MC("magma_block"), 2))
		.input(Item.of(MC("golden_axe"), 1))
		.input(Item.of(CR("experience_nugget"), 5))
		.input(Item.of(MC("gold_ingot"), 5))
		.input(Item.of(MC("quartz"), 2))
		.input(Item.of(MC("brown_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//zombified piglin
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('zombified_piglin')
		.input(Item.of(MC("netherrack"), 8))
		.input(Item.of(MC("golden_sword"), 1))
		.input(Item.of(CR("experience_nugget"), 4))
		.input(Item.of(MC("iron_ingot"), 3))
		.input(Item.of(MC("gold_ingot"), 3))
		.input(Item.of(MC("redstone"), 2))
		.input(Item.of(MC("quartz"), 4))
		.input(Item.of(MC("pink_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
	//phantom
    event.recipes.summoningrituals.altar(KJ("summoning_doll"))
		.mobOutput('phantom')
		.input(Item.of(MC("stone"), 8))
		.input(Item.of(CR("experience_nugget"), 3))
		.input(Item.of(MC("gold_ingot"), 2))
		.input(Item.of(MC("quartz"), 4))
		.input(Item.of(MC("leather"), 3))
		.input(Item.of(MC("black_dye"), 1))
		.recipeTime(200)
		.dayTime('night')
});
